import type { Food } from "@/app/lib/nutrition-types";

const MOCK_FOODS_BASE: Omit<Food, "measure" | "gramsPerUnit">[] = [
  // Proteínas
  {
    id: "pollo-pechuga",
    name: "Pechuga de pollo",
    imageUrl: "/nutrition/foods/pollo-pechuga.svg",
    category: "protein",
    servingG: 100,
    calories: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
  },
  {
    id: "carne-magra",
    name: "Carne vacuna magra",
    imageUrl: "/nutrition/foods/carne-magra.svg",
    category: "protein",
    servingG: 100,
    calories: 187,
    proteinG: 26,
    carbsG: 0,
    fatG: 9,
  },
  {
    id: "atun",
    name: "Atún al natural",
    imageUrl: "/nutrition/foods/atun.svg",
    category: "protein",
    servingG: 100,
    calories: 116,
    proteinG: 26,
    carbsG: 0,
    fatG: 1,
  },
  {
    id: "huevo",
    name: "Huevo entero",
    imageUrl: "/nutrition/foods/huevo.svg",
    category: "protein",
    servingG: 100,
    calories: 155,
    proteinG: 13,
    carbsG: 1.1,
    fatG: 11,
  },
  {
    id: "yogur-griego",
    name: "Yogur griego descremado",
    imageUrl: "/nutrition/foods/yogur-griego.svg",
    category: "protein",
    servingG: 100,
    calories: 59,
    proteinG: 10,
    carbsG: 3.6,
    fatG: 0.4,
  },
  // Carbohidratos
  {
    id: "arroz-blanco",
    name: "Arroz blanco cocido",
    imageUrl: "/nutrition/foods/arroz-blanco.svg",
    category: "carb",
    servingG: 100,
    calories: 130,
    proteinG: 2.7,
    carbsG: 28,
    fatG: 0.3,
  },
  {
    id: "avena",
    name: "Avena",
    imageUrl: "/nutrition/foods/avena.svg",
    category: "carb",
    servingG: 100,
    calories: 389,
    proteinG: 17,
    carbsG: 66,
    fatG: 7,
  },
  {
    id: "papa",
    name: "Papa hervida",
    imageUrl: "/nutrition/foods/papa.svg",
    category: "carb",
    servingG: 100,
    calories: 87,
    proteinG: 1.9,
    carbsG: 20,
    fatG: 0.1,
  },
  {
    id: "banana",
    name: "Banana",
    imageUrl: "/nutrition/foods/banana.svg",
    category: "carb",
    servingG: 100,
    calories: 89,
    proteinG: 1.1,
    carbsG: 23,
    fatG: 0.3,
  },
  {
    id: "pan-integral",
    name: "Pan integral",
    imageUrl: "/nutrition/foods/pan-integral.svg",
    category: "carb",
    servingG: 100,
    calories: 247,
    proteinG: 13,
    carbsG: 41,
    fatG: 4.2,
  },
  // Grasas
  {
    id: "palta",
    name: "Palta",
    imageUrl: "/nutrition/foods/palta.svg",
    category: "fat",
    servingG: 100,
    calories: 160,
    proteinG: 2,
    carbsG: 9,
    fatG: 15,
  },
  {
    id: "almendras",
    name: "Almendras",
    imageUrl: "/nutrition/foods/almendras.svg",
    category: "fat",
    servingG: 100,
    calories: 579,
    proteinG: 21,
    carbsG: 22,
    fatG: 50,
  },
  {
    id: "aceite-oliva",
    name: "Aceite de oliva",
    imageUrl: "/nutrition/foods/aceite-oliva.svg",
    category: "fat",
    servingG: 100,
    calories: 884,
    proteinG: 0,
    carbsG: 0,
    fatG: 100,
  },
  {
    id: "manteca-mani",
    name: "Manteca de maní",
    imageUrl: "/nutrition/foods/manteca-mani.svg",
    category: "fat",
    servingG: 100,
    calories: 588,
    proteinG: 25,
    carbsG: 20,
    fatG: 50,
  },
  // Vegetales
  {
    id: "brocoli",
    name: "Brócoli",
    imageUrl: "/nutrition/foods/brocoli.svg",
    category: "vegetable",
    servingG: 100,
    calories: 34,
    proteinG: 2.8,
    carbsG: 7,
    fatG: 0.4,
  },
  {
    id: "espinaca",
    name: "Espinaca",
    imageUrl: "/nutrition/foods/espinaca.svg",
    category: "vegetable",
    servingG: 100,
    calories: 23,
    proteinG: 2.9,
    carbsG: 3.6,
    fatG: 0.4,
  },
  {
    id: "mix-ensalada",
    name: "Mix de ensalada",
    imageUrl: "/nutrition/foods/mix-ensalada.svg",
    category: "vegetable",
    servingG: 100,
    calories: 17,
    proteinG: 1.5,
    carbsG: 2.9,
    fatG: 0.2,
  },
];

export const MOCK_FOODS: Food[] = MOCK_FOODS_BASE.map((food) => ({ ...food, measure: "g" as const, gramsPerUnit: null }));

export const MOCK_PROFILE_DEFAULTS = {
  gender: "male" as const,
  age: 28,
  heightCm: 178,
  weightKg: 78,
  bodyFatPct: null,
  activityLevel: "moderate" as const,
  goal: "recomposition" as const,
};
