-- Catalogo de alimentos AR, fase 2. Aplicar SOLO con el codigo nuevo deployado: el anterior no soporta
-- la categoria 'drink' y arranca en 100 unidades los alimentos con measure 'unit'.
-- Pasa a 'unit' lo que naturalmente se cuenta (huevos, frutas, fetas, empanadas...) y agrega las bebidas (ml = g).

do $$
declare
  missing text;
begin
  select string_agg(n.name, ', ') into missing
  from unnest(array[
    'Arepa',
    'Bagel integral',
    'Banana',
    'Barra de cereal',
    'Ciruela',
    'Crackers integrales',
    'Dátiles',
    'Durazno',
    'Galletas de arroz',
    'Kiwi',
    'Mandarina',
    'Manzana',
    'Naranja',
    'Pan árabe integral',
    'Pan de centeno',
    'Pan integral',
    'Pera',
    'Tortilla de maíz',
    'Tortilla de trigo',
    'Tostadas integrales',
    'Pan lactal blanco',
    'Pan lactal integral',
    'Pan de hamburguesa',
    'Pan de pancho',
    'Pan de miga',
    'Medialuna de manteca',
    'Medialuna de grasa',
    'Factura con dulce de leche',
    'Bizcochitos de grasa',
    'Galletitas de agua hojaldradas con grasa',
    'Tostadas de arroz',
    'Grisines',
    'Tapa de empanada',
    'Tapa de tarta',
    'Galleta marinera',
    'Tostadas de pan blanco',
    'Churro',
    'Torta frita',
    'Galletitas de agua',
    'Galletitas dulces de vainilla',
    'Galletitas rellenas',
    'Galletitas de salvado',
    'Galletitas con chips de chocolate',
    'Turrón de maní',
    'Barra de cereal con chocolate',
    'Tableta de dulce de leche',
    'Alfajor de chocolate',
    'Alfajor de maicena',
    'Helado de agua',
    'Barra crocante de arroz',
    'Higo',
    'Maracuyá',
    'Damasco',
    'Kaki',
    'Ciruela pasa',
    'Aceitunas negras',
    'Aceitunas verdes',
    'Aceituna rellena',
    'Queso de máquina en fetas',
    'Chorizo a la parrilla',
    'Morcilla',
    'Salchicha tipo viena',
    'Jamón crudo',
    'Salame',
    'Mortadela',
    'Bondiola curada en fetas',
    'Burrito de pollo',
    'Empanada de carne al horno',
    'Empanada de pollo al horno',
    'Hamburguesa completa casera',
    'Pizza integral de muzzarella',
    'Sándwich de atún integral',
    'Sándwich de pollo integral',
    'Sushi de salmón y palta',
    'Wrap vegetariano',
    'Empanada de carne frita',
    'Empanada de jamón y queso',
    'Empanada de humita',
    'Pizza de muzzarella',
    'Fugazzeta',
    'Pizza napolitana',
    'Pizza de jamón y morrones',
    'Choripán',
    'Sándwich de milanesa',
    'Lomito completo',
    'Hamburguesa con queso comercial',
    'Pancho',
    'Tostado de jamón y queso',
    'Pebete de jamón y queso',
    'Nuggets de pollo',
    'Medallón de verduras',
    'Humita en chala',
    'Chipá',
    'Sushi roll variado',
    'Clara de huevo',
    'Huevo entero',
    'Jamón cocido magro',
    'Kéfir natural',
    'Leche descremada',
    'Leche parcialmente descremada',
    'Leche entera',
    'Yogur bebible entero',
    'Yogur bebible descremado',
    'Hamburguesa de carne comercial cruda',
    'Hamburguesa de pollo comercial cruda',
    'Paleta cocida',
    'Lomito ahumado',
    'Pechuga de pavo en fetas',
    'Surimi',
    'Huevo duro',
    'Huevo frito',
    'Yema de huevo',
    'Huevo de codorniz',
    'Hamburguesa de soja',
    'Barra proteica',
    'Palmitos'
  ]::text[]) as n(name)
  where not exists (select 1 from public.foods f where f.name = n.name and f.owner_user_id is null);

  if missing is not null then
    raise exception 'Catalogo AR fase 2: faltan alimentos para pasar a unidad: %', missing;
  end if;
end $$;

update public.foods
set measure = 'unit'
where owner_user_id is null
  and grams_per_unit is not null
  and name = any (array[
    'Arepa',
    'Bagel integral',
    'Banana',
    'Barra de cereal',
    'Ciruela',
    'Crackers integrales',
    'Dátiles',
    'Durazno',
    'Galletas de arroz',
    'Kiwi',
    'Mandarina',
    'Manzana',
    'Naranja',
    'Pan árabe integral',
    'Pan de centeno',
    'Pan integral',
    'Pera',
    'Tortilla de maíz',
    'Tortilla de trigo',
    'Tostadas integrales',
    'Pan lactal blanco',
    'Pan lactal integral',
    'Pan de hamburguesa',
    'Pan de pancho',
    'Pan de miga',
    'Medialuna de manteca',
    'Medialuna de grasa',
    'Factura con dulce de leche',
    'Bizcochitos de grasa',
    'Galletitas de agua hojaldradas con grasa',
    'Tostadas de arroz',
    'Grisines',
    'Tapa de empanada',
    'Tapa de tarta',
    'Galleta marinera',
    'Tostadas de pan blanco',
    'Churro',
    'Torta frita',
    'Galletitas de agua',
    'Galletitas dulces de vainilla',
    'Galletitas rellenas',
    'Galletitas de salvado',
    'Galletitas con chips de chocolate',
    'Turrón de maní',
    'Barra de cereal con chocolate',
    'Tableta de dulce de leche',
    'Alfajor de chocolate',
    'Alfajor de maicena',
    'Helado de agua',
    'Barra crocante de arroz',
    'Higo',
    'Maracuyá',
    'Damasco',
    'Kaki',
    'Ciruela pasa',
    'Aceitunas negras',
    'Aceitunas verdes',
    'Aceituna rellena',
    'Queso de máquina en fetas',
    'Chorizo a la parrilla',
    'Morcilla',
    'Salchicha tipo viena',
    'Jamón crudo',
    'Salame',
    'Mortadela',
    'Bondiola curada en fetas',
    'Burrito de pollo',
    'Empanada de carne al horno',
    'Empanada de pollo al horno',
    'Hamburguesa completa casera',
    'Pizza integral de muzzarella',
    'Sándwich de atún integral',
    'Sándwich de pollo integral',
    'Sushi de salmón y palta',
    'Wrap vegetariano',
    'Empanada de carne frita',
    'Empanada de jamón y queso',
    'Empanada de humita',
    'Pizza de muzzarella',
    'Fugazzeta',
    'Pizza napolitana',
    'Pizza de jamón y morrones',
    'Choripán',
    'Sándwich de milanesa',
    'Lomito completo',
    'Hamburguesa con queso comercial',
    'Pancho',
    'Tostado de jamón y queso',
    'Pebete de jamón y queso',
    'Nuggets de pollo',
    'Medallón de verduras',
    'Humita en chala',
    'Chipá',
    'Sushi roll variado',
    'Clara de huevo',
    'Huevo entero',
    'Jamón cocido magro',
    'Kéfir natural',
    'Leche descremada',
    'Leche parcialmente descremada',
    'Leche entera',
    'Yogur bebible entero',
    'Yogur bebible descremado',
    'Hamburguesa de carne comercial cruda',
    'Hamburguesa de pollo comercial cruda',
    'Paleta cocida',
    'Lomito ahumado',
    'Pechuga de pavo en fetas',
    'Surimi',
    'Huevo duro',
    'Huevo frito',
    'Yema de huevo',
    'Huevo de codorniz',
    'Hamburguesa de soja',
    'Barra proteica',
    'Palmitos'
  ]::text[]);

insert into public.foods (name, image_url, category, measure, serving_g, grams_per_unit, calories, protein_g, carbs_g, fat_g, created_by)
select v.name, '', 'drink', v.measure, 100, v.grams_per_unit, v.calories, v.protein_g, v.carbs_g, v.fat_g,
  (select p.id from public.profiles p where p.type_rol = 'admin' order by p.created_at asc limit 1)
from (values
  ('Agua'::text, 'unit'::text, 200::numeric, 0::integer, 0::numeric, 0::numeric, 0::numeric),
  ('Agua saborizada'::text, 'unit'::text, 200::numeric, 21::integer, 0::numeric, 5.3::numeric, 0::numeric),
  ('Agua saborizada sin azúcar'::text, 'unit'::text, 200::numeric, 1::integer, 0::numeric, 0.3::numeric, 0::numeric),
  ('Soda'::text, 'unit'::text, 200::numeric, 0::integer, 0::numeric, 0::numeric, 0::numeric),
  ('Café negro'::text, 'unit'::text, 100::numeric, 1::integer, 0.1::numeric, 0::numeric, 0::numeric),
  ('Café con leche sin azúcar'::text, 'unit'::text, 200::numeric, 43::integer, 2.8::numeric, 4.4::numeric, 1.6::numeric),
  ('Cortado'::text, 'unit'::text, 100::numeric, 23::integer, 1.2::numeric, 2.7::numeric, 0.8::numeric),
  ('Capuchino'::text, 'unit'::text, 200::numeric, 27::integer, 1.7::numeric, 2.7::numeric, 1::numeric),
  ('Mate cebado sin azúcar'::text, 'g'::text, 250::numeric, 1::integer, 0::numeric, 0.2::numeric, 0::numeric),
  ('Mate cocido sin azúcar'::text, 'unit'::text, 200::numeric, 1::integer, 0::numeric, 0.2::numeric, 0::numeric),
  ('Té sin azúcar'::text, 'unit'::text, 200::numeric, 1::integer, 0::numeric, 0.3::numeric, 0::numeric),
  ('Gaseosa cola común'::text, 'unit'::text, 200::numeric, 40::integer, 0::numeric, 10::numeric, 0::numeric),
  ('Gaseosa cola zero'::text, 'unit'::text, 200::numeric, 0::integer, 0::numeric, 0::numeric, 0::numeric),
  ('Gaseosa lima-limón'::text, 'unit'::text, 200::numeric, 41::integer, 0.1::numeric, 10.4::numeric, 0::numeric),
  ('Agua tónica'::text, 'unit'::text, 200::numeric, 34::integer, 0::numeric, 8.8::numeric, 0::numeric),
  ('Jugo de naranja exprimido'::text, 'unit'::text, 200::numeric, 45::integer, 0.7::numeric, 10.2::numeric, 0.2::numeric),
  ('Jugo de pomelo exprimido'::text, 'unit'::text, 200::numeric, 40::integer, 0.5::numeric, 9.2::numeric, 0.1::numeric),
  ('Jugo de manzana envasado'::text, 'unit'::text, 200::numeric, 46::integer, 0.1::numeric, 11.1::numeric, 0.1::numeric),
  ('Jugo en polvo preparado'::text, 'unit'::text, 200::numeric, 25::integer, 0::numeric, 6.6::numeric, 0.1::numeric),
  ('Bebida isotónica'::text, 'unit'::text, 500::numeric, 28::integer, 0::numeric, 7::numeric, 0::numeric),
  ('Bebida energizante'::text, 'unit'::text, 250::numeric, 45::integer, 0::numeric, 11.2::numeric, 0::numeric),
  ('Leche chocolatada'::text, 'unit'::text, 200::numeric, 67::integer, 2.7::numeric, 10.9::numeric, 1.5::numeric),
  ('Licuado de banana con leche'::text, 'unit'::text, 300::numeric, 75::integer, 2.3::numeric, 12.6::numeric, 1.5::numeric),
  ('Bebida de almendras'::text, 'unit'::text, 200::numeric, 36::integer, 0.4::numeric, 6.2::numeric, 1::numeric),
  ('Bebida de almendras sin azúcar'::text, 'unit'::text, 200::numeric, 15::integer, 0.4::numeric, 1.1::numeric, 1::numeric),
  ('Bebida de soja'::text, 'unit'::text, 200::numeric, 40::integer, 2.6::numeric, 4::numeric, 1.5::numeric),
  ('Cerveza rubia'::text, 'unit'::text, 473::numeric, 43::integer, 0.5::numeric, 3.6::numeric, 0::numeric),
  ('Cerveza negra'::text, 'unit'::text, 473::numeric, 47::integer, 0::numeric, 4.2::numeric, 0::numeric),
  ('Cerveza sin alcohol'::text, 'unit'::text, 473::numeric, 25::integer, 0.4::numeric, 5.4::numeric, 0::numeric),
  ('Vino tinto'::text, 'unit'::text, 150::numeric, 84::integer, 0.1::numeric, 2.7::numeric, 0::numeric),
  ('Vino blanco'::text, 'unit'::text, 150::numeric, 83::integer, 0.1::numeric, 2.6::numeric, 0::numeric),
  ('Vino espumante'::text, 'unit'::text, 150::numeric, 83::integer, 0.1::numeric, 2.6::numeric, 0::numeric),
  ('Sidra'::text, 'unit'::text, 150::numeric, 43::integer, 0::numeric, 4.3::numeric, 0::numeric),
  ('Fernet con cola'::text, 'unit'::text, 300::numeric, 89::integer, 0::numeric, 7.8::numeric, 0.2::numeric),
  ('Gin tonic'::text, 'unit'::text, 250::numeric, 84::integer, 0::numeric, 6.6::numeric, 0::numeric),
  ('Bebida blanca destilada'::text, 'unit'::text, 45::numeric, 250::integer, 0::numeric, 0.1::numeric, 0::numeric)
) as v(name, measure, grams_per_unit, calories, protein_g, carbs_g, fat_g)
where not exists (select 1 from public.foods f where lower(f.name) = lower(v.name) and f.owner_user_id is null);
